version: '3.1'
services:
  # Stats
  stats-server:
    build: ./stats
    container_name: stats_server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=stats-db:5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  # база данных для Stats
  stats-db:
    image: postgres:14.5-alpine
    container_name: stats_db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6590:5432"
    # переменные окружения
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
